### ISSUE TITLE
Confidence intervals calculated incorrectly in anc.recon

### ISSUE THREAD

**Issue by jgvw89** [ericgoolsby/Rphylopars#23]
The formula you have in the code is:
 if(CI)
    {
      lower <- Yhat + qnorm(.975)*var
      upper <- Yhat - qnorm(.975)*var

but confidence intervals should be calculated by multiplying qnorm(.975)*sqrt(var)

Sorry if this is the wrong forum for bringing this up.

**Comment by cecileane** [comment]
You are correct! Eric, this is in `phylopars_update.R`, [l.49](https://github.com/ericgoolsby/Rphylopars/blob/937848206a29e1ecde77657c55c63ac8bcac634a/R/phylopars_update.R#L49)

**Comment by ericgoolsby** [comment]
Ah yes, thanks for catching this! The code has now been corrected (as of version 0.2.11)
