### ISSUE TITLE
ERROR: compilation failed for package ‘Rphylopars’

### ISSUE THREAD

**Issue by jailynai** [ericgoolsby/Rphylopars#24]
I can't upload the package

I don't know what happened 

the code following behind:
> require(devtools)
> library(bitops)
> library(RCurl)
> library(httr)
> set_config( config( ssl_verifypeer = 0L ) )
> install_github("ericgoolsby/Rphylopars",dependencies = TRUE)
Downloading GitHub repo ericgoolsby/Rphylopars@master
Your system is ready to build packages!
✔  checking for file ‘/private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmpCCU1Wv/remotes638d4c5086c6/ericgoolsby-Rphylopars-9378482/DESCRIPTION’ ...
─  preparing ‘Rphylopars’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:103: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:105: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:109: unexpected section header '\value'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:111: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:112: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:113: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:114: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:115: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:116: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:117: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:118: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:119: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:120: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:121: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:123: unexpected section header '\references'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:133: unexpected section header '\author'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:137: unexpected section header '\examples'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.Rd:164: unexpected END_OF_INPUT '
   '
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.lm.Rd:110: unknown macro '\item'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.lm.Rd:114: unexpected section header '\value'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.lm.Rd:117: unexpected section header '\examples'
   Warning: /private/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T/RtmprpwSmq/Rbuild657138654f11/Rphylopars/man/phylopars.lm.Rd:123: unexpected END_OF_INPUT '
   '
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘Rphylopars_0.2.10.tar.gz’
   
* installing *source* package ‘Rphylopars’ ...
** using staged installation
** libs
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c phylopars_rcpp.cpp -o phylopars_rcpp.o
phylopars_rcpp.cpp:125:11: warning: 'set_stream_err2' is deprecated [-Wdeprecated-declarations]
    arma::set_stream_err2(nullstream);
          ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/debug.hpp:99:1: note: 'set_stream_err2' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
phylopars_rcpp.cpp:128:12: warning: 'inv<arma::Mat<double> >' is deprecated [-Wdeprecated-declarations]
    Minv = inv(M,"std");    
           ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_inv.hpp:60:1: note: 'inv<arma::Mat<double> >' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
phylopars_rcpp.cpp:144:11: warning: 'set_stream_err2' is deprecated [-Wdeprecated-declarations]
    arma::set_stream_err2(nullstream);
          ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/debug.hpp:99:1: note: 'set_stream_err2' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
phylopars_rcpp.cpp:146:14: warning: 'solve<arma::Mat<double>, arma::Mat<double> >' is deprecated [-Wdeprecated-declarations]
    Msolve = solve(M,V,"std");
             ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/fn_solve.hpp:67:1: note: 'solve<arma::Mat<double>, arma::Mat<double> >' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
phylopars_rcpp.cpp:179:11: warning: 'set_stream_err2' is deprecated [-Wdeprecated-declarations]
    arma::set_stream_err2(nullstream);
          ^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/debug.hpp:99:1: note: 'set_stream_err2' has been explicitly marked deprecated here
arma_deprecated
^
/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppArmadillo/include/armadillo_bits/compiler_setup.hpp:303:44: note: expanded from macro 'arma_deprecated'
    #define arma_deprecated __attribute__((__deprecated__))
                                           ^
5 warnings generated.
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Rphylopars.so RcppExports.o phylopars_rcpp.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Rphylopars.so] Error 1
ERROR: compilation failed for package ‘Rphylopars’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rphylopars’
Error: Failed to install 'Rphylopars' from GitHub:
  (converted from warning) installation of package ‘/var/folders/v2/pjk2jy6530q27qj22dyhkzgc0000gn/T//RtmpCCU1Wv/file638d29e58704/Rphylopars_0.2.10.tar.gz’ had non-zero exit status

**Comment by r03ert0** [comment]
maybe you need to install gfortran first?

**Comment by ntraut** [comment]
If you are under a new version of macOS, maybe you have to reconfigure the R toolchain for compilation. See:
https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/
