### ISSUE TITLE
Imputation method for compositional data?

### ISSUE THREAD

**Issue by diogoprov** [ericgoolsby/Rphylopars#45]
Hi @ericgoolsby , I have a particular dataset in hand that is a compositional data, i.e., percentages of white blood cell types in 48 frog species. There're 30 species lacking data, this is the distribution of the data
![leuko_missing](https://user-images.githubusercontent.com/5214836/114276426-86f1de00-99f4-11eb-90c0-6bf25d756d3e.jpeg)

I tested multiple models of trait evoltution and it seems that BM is the best one (less variation), but the problem is: the data for each species has to sum to 100%. This is because the data consists of percentages of each blood cell type (e.g., lymphocyte had 60%, neutrophils 10% and so on). Is there any way for me to impose some kind of contraint in the estimation under BM that says that, say, the rowSums of each species has to sum to 100%?

Thank you,
Diogo

**Comment by diogoprov** [comment]
And this is what is happening

![leuko_stackedbar](https://user-images.githubusercontent.com/5214836/114276863-85291a00-99f6-11eb-8c86-88e974d4d71c.jpeg)

**Comment by FVFaleiro** [comment]
Hi @diogoprov that's a interesting question. How did you solve it? I think you could share the solution here to help others.
Cheers!

**Comment by diogoprov** [comment]
Oh man, I realized that the error was becuase I was including one variable (total Leukocytes) that was not supposed to sum to 100%. Removing this variable makes the imputed dataset almost perfect, with only one or two species having more or less than 100%. So it seems Rphylopars works in a bunch of different and challenging scenarios. 
Changing from BM to OU or EB didn't improve the estimations of missing values anyway
