### ISSUE TITLE
Plan to re-add to CRAN?

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [ericgoolsby/Rphylopars#58]
I'm including a comparison with Rphylopars in my R-package [phylosem](https://cran.r-project.org/web/packages/Rphylopars/index.html).  However, it appears that Rphylopars was recently removed from CRAN.  Do y'all intend to re-add it?

And of course:  thanks for all the effort involved regardless of how you proceed!

**Comment by ericgoolsby** [comment]
Hi James, yeah sorry about that! They notified me over the holidays so I didn't even see their messages until it was too late to resubmit in time. I've patched the code, and I'm just running final CRAN checks and I'll be submitting by the end of the week. So hopefully it's back on CRAN by early next week!

**Comment by James-Thorson-NOAA** [comment]
awesome! thanks for the update, and I'm glad to hear that it'll still be available.
