### ISSUE TITLE
Singular system on large data-set with a lot of overlap

### ISSUE THREAD

**Issue by evangorstein** [ericgoolsby/Rphylopars#59]
I was hoping to use `phylopars()` to fit a two-dimensional Brownian motion model along a tree with ~5000 tips.

A plot of the two-dimensional species "traits" is shown below:
![image](https://github.com/user-attachments/assets/467d9109-2fb6-48b9-a4c9-cd15729bba2f)
And the actual tree
![image](https://github.com/user-attachments/assets/784ab081-3adb-4cc8-9276-a4c923e28070)
(Colors in the two plots correspond)

When I fit the model, I get the following messages:

```
warning: solve(): system is singular; attempting approx solution

warning: solve(): system is singular; attempting approx solution
Error: Not a matrix.
```

However, if I sample the tips of the tree (with ape::keep.tip()) to create a thinned out tree with only 750 tips, then `phylopars()` runs without error on this smaller dataset. The downsampled tree and trait scatterplot are visualized below:
![image](https://github.com/user-attachments/assets/dea2154c-122a-4fd5-8d3d-3144eeedf1b6)
![image](https://github.com/user-attachments/assets/b95f81f4-bd73-4d0f-b018-85831af3579e)

Do you know what the source for the matrix singularity and the resulting error on the larger dataset is? One possibility that I checked was if the larger tree has any pairs of external branches, which are sisters and which are both (near) length 0, but the error remains if I get rid of such pairs of short sister external branches from the large tree.

**Comment by ericgoolsby** [comment]
The singular matrix can happen from any tips with zero or near-zero branch lengths. You could check for that with something like `sort(tree$edge.length[which(tree$edge[,2]<=length(tree$tip.label))])` The relative scaling matters too, so maybe check to see what the shortest tip length is divided by tree height.

Other possibilities: do you have any species with more than one observation, or missing data?

**Comment by evangorstein** [comment]
Ahh, getting rid of the short external branches did the trick! Thanks so much!
